# Standard Sobol analysis
# Note: if you want to run the code for a replication check, all the output results should be the same as
#       the example outputs except for the computational time (because the machines are different). 
#       This note applies to all the scripts in this study.

# Remove all existing environment and plots
rm(list = ls())
graphics.off()

# Set a working directory, please set it to your own working folder when testing
dir <- "/storage/work/h/hxy46/Sensitivity"
setwd(dir = dir)

# Load the required package
library(sensobol)

# The dimensions we consider
D <- c(2,5,10,15,20,30)

# The list of sample sizes we consider
tot_size <- c(seq(1000,10000,by=1000),seq(15000,95000,by=5000),seq(100000,200000,by=10000))

# Define the test model in each dimension and perform the Sobol analysis
for (k in 1:length(D)){
  # d dimensional model
  d <- D[k]
  # Reliability is the test model's name
  Reliability<-function (X) {
    S = 0
    for (i in 1:d){
      if (i%%3==1){
        a = 1
        b = X[i]
      } else if (i%%3==2){
        a = 10
        b = X[i]^2*X[i-1]
      } else {
        a = 100
        b = X[i]
      }
      S = S + a*b
    }
    return(S)
  }
  
  # Folder for d dimension test scenario under the working directory
  # "Data" is the folder that saves all the relevant parameters during the tests
  folder<-paste("/Example_Data/",d,"D",sep="")
  dir.create(paste(folder,"/Sobol",sep=""), recursive = TRUE)
  
  # For each considered sample size, perform the Sobol analysis
  for (m in 1:length(tot_size)){
    
    # "sensobol" package has a special design for a sobol matrix used for the analysis,
    #     N here is the length of the matrix.
    # The relationship between N and the sample size (when calculating up to 2nd order indices) is:
    #     sample size = N*(d+2+d*(d-1)/2)
    # Note we take the nearest integer, hence the actual sample size is an approximation of the list of sample
    #     size we consider. 
    N <- floor(tot_size[m]/(d+2+d*(d-1)/2))
    # Input matrix and output. The input matrix is generated by the Sobol sequence algorithm.
    mat <- sobol_matrices(N = N, params = as.character(c(1:d)), order = "second")
    X <- split(t(mat), rep(1:dim(mat)[1], each = d))
    
    # Model total evaluation time
    start.time<-Sys.time()
    Y <- sapply(X, Reliability)
    end.time<-Sys.time()
    
    # Model average evaluation time
    avg_eval_time <- difftime(end.time,start.time,units = "secs")/length(Y)
    
    # Sensitivity analysis time
    start.time<-Sys.time()
    S <- sobol_indices(Y=Y,N=N,params = as.character(c(1:d)),
                       boot=TRUE,R=100,order="second")
    end.time<-Sys.time()
    T_Sobol<-difftime(end.time,start.time,units = "secs")
    
    # Convergence check: if all total-order sensitivity indices have a 95%CI width within 0.05, then it is converged
    Range <- S$results$high.ci[(d+1):(2*d)]-S$results$low.ci[(d+1):(2*d)]
    if (all(Range<=0.05)){
      
      # If convergence is reached, create the folder of standard Sobol analysis and save the results of:
      #     (1) Average model evaluation time
      #     (2) Sensitivity indices
      #     (3) Time of the Sobol analysis
      save(avg_eval_time,file = paste(folder,"/avg_eval_time",sep=""))
      save(S,file = paste(folder,"/Sobol/S_Sobol",sep=""))
      save(T_Sobol,file = paste(folder,"/Sobol/T_Sobol",sep=""))
      break
    }
  }
}

# Finally, save the convergence size of each model dimension into a vector
Sobol_convergesize <- rep(NA,length(D))
for (i in 1:length(D)) {
  folder <- paste("/Example_Data/",D[i],"D/Sobol",sep="")
  load(paste(folder,"/S_Sobol",sep=""))
  Sobol_convergesize[i] <- S$C
}
save(Sobol_convergesize,file = "/Example_Data/Sobol_convergencesize")
